### PR TITLE
Use `files` property in package.json

### PR DESCRIPTION
**Pull request by kevva**

### CODE REVIEW

**Comment by felixge** [comment]
What does this do? Looking at https://docs.npmjs.com/files/package.json it seems like it's going to only include the lib directory? Why do you want that? It would violate the MIT license (because it would get excluded).

**Comment by kevva** [comment]
No, the readme and license is included automatically.

**Comment by felixge** [comment]
But what are you trying to accomplish? The `.npmignore` in this project already excludes the tests.

**Comment by kevva** [comment]
Depends if you favor whitelisting or blacklisting files. I'm just trying to save some bytes here. Noone seem to care about updating their `.npmignore` files which leads to unnecessary stuff getting included.

**Comment by kevva** [comment]
ping @felixge. Close if you don't want this :).

**Comment by mike-zorn** [comment]
Interesting idea. I think `.npmignore` is sufficient for this module: I'd be a little concerned about remembering to edit `files` whenever I added a new file outside of lib. Thanks for the suggestion, though.

**Pull request closed without merging**
